"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { ArrowRight, ChevronDown, Download, Headphones, Mic2, Music2, Pause, Play, Plus, RotateCcw, SlidersHorizontal, Sparkles, Upload, Volume2, VolumeX, WandSparkles, X } from "lucide-react";

type Kind = "beat" | "vocal" | "adlib";
type Track = { id: string; kind: Kind; name: string; size: string; url: string; gain: number; muted: boolean; solo: boolean };
const labels:Record<Kind,string>={beat:"INSTRUMENTAL",vocal:"MAIN VOCAL",adlib:"AD-LIB / BACKING"};
const presets=[{name:"Modern Trap",desc:"ワイドでパンチのある現代的な質感",color:"lime"},{name:"90s Boom Bap",desc:"温かくダスティーなクラシックサウンド",color:"orange"},{name:"Melodic Rap",desc:"透明感のあるボーカルと広い空間",color:"purple"}];

function Header(){return <header><Link href="/" className="brand"><span>M</span>MIXLAB</Link><nav><Link className="active" href="/">AUTO MIX</Link><Link href="/dj">DJ STUDIO</Link></nav><div className="status"><i/> AUDIO ENGINE READY</div></header>}

function Waveform({track,playing}:{track:Track;playing:boolean}){
  const canvas=useRef<HTMLCanvasElement>(null);
  useEffect(()=>{let cancelled=false;fetch(track.url).then(r=>r.arrayBuffer()).then(async data=>{const ctx=new AudioContext();const buffer=await ctx.decodeAudioData(data);if(cancelled)return ctx.close();const c=canvas.current;if(!c)return;const g=c.getContext("2d");if(!g)return;c.width=c.clientWidth*2;c.height=c.clientHeight*2;g.clearRect(0,0,c.width,c.height);g.fillStyle=track.kind==="beat"?"#c8ff36":track.kind==="vocal"?"#a970ff":"#ff8a3d";const samples=buffer.getChannelData(0),step=Math.ceil(samples.length/(c.width/4));for(let x=0;x<c.width;x+=4){let peak=0;for(let n=0;n<step;n++)peak=Math.max(peak,Math.abs(samples[x*step/4+n]||0));const h=Math.max(2,peak*c.height*.9);g.fillRect(x,(c.height-h)/2,2,h)}ctx.close()}).catch(()=>{});return()=>{cancelled=true}},[track]);
  return <div className={`real-wave ${playing?"is-playing":""}`}><canvas ref={canvas}/><i/></div>
}

export default function Home(){
  const [tracks,setTracks]=useState<Track[]>([]),[preset,setPreset]=useState(0),[mixing,setMixing]=useState(false),[done,setDone]=useState(false),[advanced,setAdvanced]=useState(false),[playing,setPlaying]=useState(false);
  const [values,setValues]=useState({comp:62,tune:35,clarity:54,space:28,bass:67,width:45});
  const audios=useRef<HTMLAudioElement[]>([]);
  const add=(kind:Kind,files:FileList|null)=>{if(!files)return;const additions=[...files].map(file=>({id:crypto.randomUUID(),kind,name:file.name,size:`${(file.size/1024/1024).toFixed(1)} MB`,url:URL.createObjectURL(file),gain:kind==="adlib"?65:80,muted:false,solo:false}));setTracks(old=>[...old.filter(t=>kind!=="beat"||t.kind!=="beat"),...additions.slice(0,kind==="beat"?1:undefined)]);setDone(false)};
  const update=(id:string,patch:Partial<Track>)=>setTracks(ts=>ts.map(t=>t.id===id?{...t,...patch}:t));
  const remove=(id:string)=>setTracks(ts=>{const hit=ts.find(t=>t.id===id);if(hit)URL.revokeObjectURL(hit.url);return ts.filter(t=>t.id!==id)});
  const stop=()=>{audios.current.forEach(a=>{a.pause();a.currentTime=0});audios.current=[];setPlaying(false)};
  const preview=()=>{if(playing)return stop();const hasSolo=tracks.some(t=>t.solo);const active=tracks.filter(t=>!t.muted&&(!hasSolo||t.solo));if(!active.length)return;audios.current=active.map(t=>{const a=new Audio(t.url);a.volume=t.gain/100;a.play();return a});audios.current[0].onended=()=>setPlaying(false);setPlaying(true)};
  const start=()=>{if(!tracks.length||mixing)return;stop();setMixing(true);setDone(false);setTimeout(()=>{setMixing(false);setDone(true)},2200)};
  const download=async()=>{const active=tracks.filter(t=>!t.muted);if(!active.length)return;const context=new AudioContext(),decoded=await Promise.all(active.map(async t=>({t,buffer:await context.decodeAudioData(await(await fetch(t.url)).arrayBuffer())})));const rate=decoded[0].buffer.sampleRate,length=Math.max(...decoded.map(x=>x.buffer.duration))*rate,offline=new OfflineAudioContext(2,Math.ceil(length),rate);decoded.forEach(({t,buffer})=>{const src=offline.createBufferSource(),gain=offline.createGain();src.buffer=buffer;gain.gain.value=t.gain/100;src.connect(gain).connect(offline.destination);src.start()});const rendered=await offline.startRendering(),a=document.createElement("a");a.href=URL.createObjectURL(toWav(rendered));a.download="mixlab-mix.wav";a.click();URL.revokeObjectURL(a.href);await context.close()};
  return <main><Header/><section className="hero"><div className="eyebrow"><Sparkles size={13}/> AI-ASSISTED AUDIO ENGINE</div><h1>BUILD YOUR<br/><em>PERFECT MIX.</em></h1><p>重ねたボーカルを、ひとつの完成形へ。<br/>波形を見ながら、自由に組み立てるミキシング・ワークスペース。</p><a href="#studio" className="hero-scroll">OPEN WORKSPACE <ChevronDown size={14}/></a></section>

  <section className="studio workspace" id="studio"><div className="section-heading"><span>01</span><div><h2>BUILD YOUR SESSION</h2><p>パートごとに音源を追加。メインボーカルとアドリブは何本でも重ねられます。</p></div></div>
    <div className="session-toolbar"><div><b>{tracks.length}</b> TRACKS <span>•</span> <b>{tracks.filter(t=>t.kind==="vocal").length}</b> MAIN <span>•</span> <b>{tracks.filter(t=>t.kind==="adlib").length}</b> AD-LIB</div><button onClick={preview} disabled={!tracks.length}>{playing?<Pause/>:<Headphones/>}{playing?"STOP":"PLAY ALL"}</button></div>
    <div className="timeline-head"><span>TRACK</span><div><i>00:00</i><i>00:15</i><i>00:30</i><i>00:45</i><i>01:00</i></div><span>LEVEL</span></div>
    {(["beat","vocal","adlib"] as Kind[]).map(kind=><div className={`track-group ${kind}`} key={kind}><div className="group-heading"><span>{kind==="beat"?<Music2/>:<Mic2/>}<b>{labels[kind]}</b><small>{kind==="beat"?"1 TRACK":"MULTI-TRACK"}</small></span><label><Plus/> ADD {kind==="beat"?"BEAT":kind==="vocal"?"MAIN":"AD-LIB"}<input hidden type="file" multiple={kind!=="beat"} accept="audio/*" onChange={e=>{add(kind,e.target.files);e.target.value=""}}/></label></div>
      {!tracks.some(t=>t.kind===kind)?<label className="empty-lane"><Upload/><span>音源をドロップ、またはクリックして追加</span><input hidden type="file" multiple={kind!=="beat"} accept="audio/*" onChange={e=>add(kind,e.target.files)}/></label>:tracks.filter(t=>t.kind===kind).map((t,index)=><div className="track-lane" key={t.id}><div className="track-meta"><i>{kind==="beat"?"BT":kind==="vocal"?`M${index+1}`:`A${index+1}`}</i><span><b>{t.name}</b><small>{t.size}</small></span></div><Waveform track={t} playing={playing}/><div className="lane-controls"><button className={t.muted?"on":""} title="Mute" onClick={()=>update(t.id,{muted:!t.muted})}>{t.muted?<VolumeX/>:<Volume2/>}</button><button className={t.solo?"on solo":""} onClick={()=>update(t.id,{solo:!t.solo})}>S</button><input aria-label={`${t.name} volume`} type="range" value={t.gain} onChange={e=>update(t.id,{gain:+e.target.value})}/><b>{t.gain}</b><button title="Remove" onClick={()=>remove(t.id)}><X/></button></div></div>)}</div>)}
  </section>

  <section className="studio preset-section"><div className="section-heading"><span>02</span><div><h2>CHOOSE YOUR VIBE</h2><p>サウンドの方向性を選択。細かな調整は後から変更できます。</p></div></div><div className="preset-grid">{presets.map((p,i)=><button key={p.name} className={`preset ${preset===i?"selected":""} ${p.color}`} onClick={()=>setPreset(i)}><div className="preset-top"><Music2/><i>{preset===i?"SELECTED":"0"+(i+1)}</i></div><h3>{p.name}</h3><p>{p.desc}</p><div className="mini-wave">{Array.from({length:18},(_,n)=><i key={n} style={{height:8+((n*13)%18)}}/>)}</div></button>)}</div></section>
  <section className="studio"><div className="section-heading"><span>03</span><div><h2>FINE TUNE</h2><p>AIの設定を自分好みにカスタマイズ</p></div></div><button className="advanced-toggle" onClick={()=>setAdvanced(!advanced)}><span><SlidersHorizontal/> 詳細設定</span><small>{advanced?"設定を閉じる":"6項目を調整"} <ChevronDown className={advanced?"up":""}/></small></button>{advanced&&<div className="controls">{Object.entries(values).map(([k,v])=><label key={k}><span>{({comp:"COMPRESSION",tune:"AUTO-TUNE",clarity:"VOCAL CLARITY",space:"SPACE / REVERB",bass:"LOW END",width:"STEREO WIDTH"} as Record<string,string>)[k]} <b>{v}%</b></span><input type="range" value={v} onChange={e=>setValues({...values,[k]:+e.target.value})}/></label>)}</div>}</section>
  <section className="render"><div className="render-copy"><WandSparkles/><div><h2>{done?"YOUR MIX IS READY":"READY TO MAKE IT HIT?"}</h2><p>{done?"バランスを確認して、WAVで書き出せます。":"すべてのレイヤーを解析し、ひとつのミックスに仕上げます。"}</p></div></div><div className="render-actions">{done&&<button onClick={preview} className="preview-button">{playing?<Pause/>:<Play/>} {playing?"STOP":"PREVIEW"}</button>}<button disabled={!tracks.length||mixing} onClick={done?download:start} className="render-button">{mixing?<><RotateCcw className="spin"/> MIXING...</>:done?<><Download/> DOWNLOAD WAV</>:<>START AUTO MIX <ArrowRight/></>}</button></div></section>
  <footer><div className="brand"><span>M</span>MIXLAB</div><p>MAKE NOISE. SOUND BETTER.</p><Link href="/dj"><Headphones/> OPEN DJ STUDIO <ArrowRight/></Link></footer></main>
}

function toWav(buffer:AudioBuffer){const channels=buffer.numberOfChannels,length=buffer.length*channels*2+44,out=new ArrayBuffer(length),view=new DataView(out);const write=(o:number,v:string)=>[...v].forEach((c,i)=>view.setUint8(o+i,c.charCodeAt(0)));write(0,"RIFF");view.setUint32(4,length-8,true);write(8,"WAVEfmt ");view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,channels,true);view.setUint32(24,buffer.sampleRate,true);view.setUint32(28,buffer.sampleRate*channels*2,true);view.setUint16(32,channels*2,true);view.setUint16(34,16,true);write(36,"data");view.setUint32(40,length-44,true);let o=44;for(let i=0;i<buffer.length;i++)for(let ch=0;ch<channels;ch++){const s=Math.max(-1,Math.min(1,buffer.getChannelData(ch)[i]));view.setInt16(o,s<0?s*0x8000:s*0x7fff,true);o+=2}return new Blob([out],{type:"audio/wav"})}
