"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { LanguageSelect, useI18n } from "./i18n";
import { ArrowRight, ChevronDown, Download, Headphones, Mic2, Music2, Pause, Play, Plus, RotateCcw, SlidersHorizontal, Sparkles, Upload, Volume2, VolumeX, WandSparkles, X } from "lucide-react";

type Kind = "beat" | "vocal" | "adlib";
type Plugins = { comp: number; low: number; mid: number; high: number };
type Track = { id: string; kind: Kind; name: string; size: string; url: string; gain: number; muted: boolean; solo: boolean; plugins: Plugins };
const labels:Record<Kind,string>={beat:"Instrumental",vocal:"Main vocal",adlib:"Ad-lib / backing"};
const presets=[{name:"Modern Trap",desc:"Wide and punchy with a modern edge",color:"lime"},{name:"90s Boom Bap",desc:"Warm, dusty, and classic",color:"orange"},{name:"Melodic Rap",desc:"Clear vocals with a spacious feel",color:"purple"}];
const defaultPlugins:Record<Kind,Plugins>={beat:{comp:25,low:0,mid:0,high:0},vocal:{comp:62,low:-2,mid:2,high:3},adlib:{comp:48,low:-4,mid:1,high:2}};

function Header(){const {t}=useI18n();return <header><Link href="/" className="brand"><span>M</span>MIXLAB</Link><nav><Link className="active" href="/">AUTO MIX</Link><Link href="/dj">DJ STUDIO</Link></nav><div className="status"><i/> {t("Audio engine ready").toUpperCase()}</div><LanguageSelect/></header>}

function Waveform({track,playing,currentTime,onSeek}:{track:Track;playing:boolean;currentTime:number;onSeek:(time:number)=>void}){
  const canvas=useRef<HTMLCanvasElement>(null);
  const [duration,setDuration]=useState(0);
  useEffect(()=>{let cancelled=false;fetch(track.url).then(r=>r.arrayBuffer()).then(async data=>{const ctx=new AudioContext();const buffer=await ctx.decodeAudioData(data);if(cancelled)return ctx.close();setDuration(buffer.duration);const c=canvas.current;if(!c)return;const g=c.getContext("2d");if(!g)return;c.width=c.clientWidth*2;c.height=c.clientHeight*2;g.clearRect(0,0,c.width,c.height);g.fillStyle=track.kind==="beat"?"#c8ff36":track.kind==="vocal"?"#a970ff":"#ff8a3d";const samples=buffer.getChannelData(0),step=Math.ceil(samples.length/(c.width/4));for(let x=0;x<c.width;x+=4){let peak=0;for(let n=0;n<step;n++)peak=Math.max(peak,Math.abs(samples[x*step/4+n]||0));const h=Math.max(2,peak*c.height*.9);g.fillRect(x,(c.height-h)/2,2,h)}ctx.close()}).catch(()=>{});return()=>{cancelled=true}},[track]);
  const progress=duration?Math.min(currentTime/duration,1)*100:0;
  const seek=(clientX:number,element:HTMLElement)=>{if(!duration)return;const rect=element.getBoundingClientRect();onSeek(Math.max(0,Math.min(1,(clientX-rect.left)/rect.width))*duration)};
  return <div className={`real-wave ${playing?"is-playing":""}`} role="slider" aria-label={`${track.name} playback position`} aria-valuemin={0} aria-valuemax={Math.round(duration)} aria-valuenow={Math.round(Math.min(currentTime,duration))} tabIndex={0} onClick={e=>seek(e.clientX,e.currentTarget)} onKeyDown={e=>{if(!duration)return;if(e.key==="ArrowLeft"||e.key==="ArrowRight"){e.preventDefault();onSeek(Math.max(0,Math.min(duration,currentTime+(e.key==="ArrowRight"?5:-5))))}}}><canvas ref={canvas}/><i style={{left:`${progress}%`}}/></div>
}

export default function Home(){
  const {t:tr}=useI18n();
  const [tracks,setTracks]=useState<Track[]>([]),[preset,setPreset]=useState(0),[mixing,setMixing]=useState(false),[done,setDone]=useState(false),[advanced,setAdvanced]=useState(false),[playing,setPlaying]=useState(false),[previewTime,setPreviewTime]=useState(0),[downloading,setDownloading]=useState(false),[editingTrack,setEditingTrack]=useState<string|null>(null);
  const [values,setValues]=useState({comp:62,tune:35,clarity:54,space:28,bass:67,width:45});
  const audios=useRef<HTMLAudioElement[]>([]),previewContext=useRef<AudioContext|null>(null),previewFrame=useRef<number|null>(null),downloadLock=useRef(false);
  const add=(kind:Kind,files:FileList|null)=>{if(!files)return;const additions=[...files].map(file=>({id:crypto.randomUUID(),kind,name:file.name,size:`${(file.size/1024/1024).toFixed(1)} MB`,url:URL.createObjectURL(file),gain:kind==="adlib"?65:80,muted:false,solo:false,plugins:{...defaultPlugins[kind]}}));setTracks(old=>[...old.filter(t=>kind!=="beat"||t.kind!=="beat"),...additions.slice(0,kind==="beat"?1:undefined)]);setDone(false)};
  const update=(id:string,patch:Partial<Track>)=>setTracks(ts=>ts.map(t=>t.id===id?{...t,...patch}:t));
  const remove=(id:string)=>setTracks(ts=>{const hit=ts.find(t=>t.id===id);if(hit)URL.revokeObjectURL(hit.url);return ts.filter(t=>t.id!==id)});
  const stop=()=>{if(previewFrame.current!==null)cancelAnimationFrame(previewFrame.current);previewFrame.current=null;audios.current.forEach(a=>{a.pause();a.currentTime=0});audios.current=[];previewContext.current?.close();previewContext.current=null;setPreviewTime(0);setPlaying(false)};
  const preview=()=>{if(playing)return stop();const hasSolo=tracks.some(t=>t.solo);const active=tracks.filter(t=>!t.muted&&(!hasSolo||t.solo));if(!active.length)return;const context=new AudioContext();previewContext.current=context;audios.current=active.map(t=>{const a=new Audio(t.url),source=context.createMediaElementSource(a);a.currentTime=previewTime;connectPlugins(context,source,context.destination,t);a.play();a.onended=()=>{if(audios.current.every(audio=>audio.ended))stop()};return a});const updatePlayhead=()=>{setPreviewTime(Math.max(0,...audios.current.map(a=>a.currentTime)));previewFrame.current=requestAnimationFrame(updatePlayhead)};updatePlayhead();setPlaying(true)};
  const seekPreview=(time:number)=>{setPreviewTime(time);audios.current.forEach(a=>{a.currentTime=Math.min(time,Number.isFinite(a.duration)?a.duration:time)})};
  const start=()=>{if(!tracks.length||mixing)return;stop();setMixing(true);setDone(false);setTimeout(()=>{setMixing(false);setDone(true)},2200)};
  const download=async()=>{if(downloadLock.current)return;const active=tracks.filter(t=>!t.muted);if(!active.length)return;downloadLock.current=true;setDownloading(true);let context:AudioContext|null=null;try{context=new AudioContext();const decoded=await Promise.all(active.map(async t=>({t,buffer:await context!.decodeAudioData(await(await fetch(t.url)).arrayBuffer())})));const rate=decoded[0].buffer.sampleRate,length=Math.max(...decoded.map(x=>x.buffer.duration))*rate,offline=new OfflineAudioContext(2,Math.ceil(length),rate);decoded.forEach(({t,buffer})=>{const src=offline.createBufferSource();src.buffer=buffer;connectPlugins(offline,src,offline.destination,t);src.start()});const rendered=await offline.startRendering(),a=document.createElement("a"),downloadUrl=URL.createObjectURL(toWav(rendered));a.href=downloadUrl;a.download="mixlab-mix.wav";a.click();setTimeout(()=>URL.revokeObjectURL(downloadUrl),0)}finally{await context?.close();downloadLock.current=false;setDownloading(false)}};
  return <main><Header/><section className="hero"><div className="eyebrow"><Sparkles size={13}/> AI-ASSISTED AUDIO ENGINE</div><h1>{tr("Build your perfect mix.").toUpperCase()}</h1><p>{tr("Layer your vocals into one finished track.")}<br/>{tr("Shape your sound freely in a waveform-based mixing workspace.")}</p><a href="#studio" className="hero-scroll">{tr("Open workspace").toUpperCase()} <ChevronDown size={14}/></a></section>

  <section className="studio workspace" id="studio"><div className="section-heading"><span>01</span><div><h2>{tr("Build your session").toUpperCase()}</h2><p>{tr("Add audio by part. Layer as many main vocals and ad-libs as you need.")}</p></div></div>
    <div className="session-toolbar"><div><b>{tracks.length}</b> {tr("Tracks").toUpperCase()} <span>•</span> <b>{tracks.filter(t=>t.kind==="vocal").length}</b> {tr("Main").toUpperCase()} <span>•</span> <b>{tracks.filter(t=>t.kind==="adlib").length}</b> AD-LIB</div><button onClick={preview} disabled={!tracks.length}>{playing?<Pause/>:<Headphones/>}{tr(playing?"Stop":"Play all").toUpperCase()}</button></div>
    <div className="timeline-head"><span>{tr("Track").toUpperCase()}</span><div><i>00:00</i><i>00:15</i><i>00:30</i><i>00:45</i><i>01:00</i></div><span>{tr("Level").toUpperCase()}</span></div>
    {(["beat","vocal","adlib"] as Kind[]).map(kind=><div className={`track-group ${kind}`} key={kind}><div className="group-heading"><span>{kind==="beat"?<Music2/>:<Mic2/>}<b>{tr(labels[kind]).toUpperCase()}</b><small>{kind==="beat"?`1 ${tr("Track").toUpperCase()}`:tr("Multi-track").toUpperCase()}</small></span><label><Plus/> {tr(kind==="beat"?"Add beat":kind==="vocal"?"Add main":"Add ad-lib").toUpperCase()}<input hidden type="file" multiple={kind!=="beat"} accept="audio/*" onChange={e=>{add(kind,e.target.files);e.target.value=""}}/></label></div>
      {!tracks.some(t=>t.kind===kind)?<label className="empty-lane"><Upload/><span>{tr("Drop audio here or click to add")}</span><input hidden type="file" multiple={kind!=="beat"} accept="audio/*" onChange={e=>add(kind,e.target.files)}/></label>:tracks.filter(t=>t.kind===kind).map((t,index)=><div className="track-wrap" key={t.id}><div className="track-lane"><div className="track-meta"><i>{kind==="beat"?"BT":kind==="vocal"?`M${index+1}`:`A${index+1}`}</i><span><b>{t.name}</b><small>{t.size}</small></span></div><Waveform track={t} playing={playing} currentTime={previewTime} onSeek={seekPreview}/><div className="lane-controls"><button className={t.muted?"on":""} title="Mute" onClick={()=>update(t.id,{muted:!t.muted})}>{t.muted?<VolumeX/>:<Volume2/>}</button><button className={t.solo?"on solo":""} onClick={()=>update(t.id,{solo:!t.solo})}>S</button><input aria-label={`${t.name} volume`} type="range" value={t.gain} onChange={e=>update(t.id,{gain:+e.target.value})}/><b>{t.gain}</b><button className={editingTrack===t.id?"on plugin-button":"plugin-button"} title={tr("Track plug-ins")} onClick={()=>setEditingTrack(editingTrack===t.id?null:t.id)}><SlidersHorizontal/></button><button title="Remove" onClick={()=>remove(t.id)}><X/></button></div></div>{editingTrack===t.id&&<div className="track-plugins"><div className="plugin-title"><span><SlidersHorizontal/><b>{tr("Track plug-ins").toUpperCase()}</b></span><small>{tr("Applied only to this audio")}</small><button onClick={()=>update(t.id,{plugins:{...defaultPlugins[kind]}})}><RotateCcw/> {tr("Reset").toUpperCase()}</button></div><div className="plugin-controls"><PluginSlider label="COMPRESS" value={t.plugins.comp} unit="%" min={0} max={100} onChange={value=>update(t.id,{plugins:{...t.plugins,comp:value}})}/>{(["low","mid","high"] as const).map(key=><PluginSlider key={key} label={`EQ ${key.toUpperCase()}`} value={t.plugins[key]} unit="dB" min={-12} max={12} onChange={value=>update(t.id,{plugins:{...t.plugins,[key]:value}})}/>)}</div></div>}</div>)}</div>)}
  </section>

  <section className="studio preset-section"><div className="section-heading"><span>02</span><div><h2>{tr("Choose your vibe").toUpperCase()}</h2><p>{tr("Choose a direction for your sound. You can fine-tune it later.")}</p></div></div><div className="preset-grid">{presets.map((p,i)=><button key={p.name} className={`preset ${preset===i?"selected":""} ${p.color}`} onClick={()=>setPreset(i)}><div className="preset-top"><Music2/><i>{preset===i?tr("Selected").toUpperCase():"0"+(i+1)}</i></div><h3>{tr(p.name)}</h3><p>{tr(p.desc)}</p><div className="mini-wave">{Array.from({length:18},(_,n)=><i key={n} style={{height:8+((n*13)%18)}}/>)}</div></button>)}</div></section>
  <section className="studio"><div className="section-heading"><span>03</span><div><h2>{tr("Fine tune").toUpperCase()}</h2><p>{tr("Customize the AI settings to fit your sound.")}</p></div></div><button className="advanced-toggle" onClick={()=>setAdvanced(!advanced)}><span><SlidersHorizontal/> {tr("Advanced settings")}</span><small>{tr(advanced?"Close settings":"Adjust 6 controls")} <ChevronDown className={advanced?"up":""}/></small></button>{advanced&&<div className="controls">{Object.entries(values).map(([k,v])=><label key={k}><span>{({comp:"COMPRESSION",tune:"AUTO-TUNE",clarity:"VOCAL CLARITY",space:"SPACE / REVERB",bass:"LOW END",width:"STEREO WIDTH"} as Record<string,string>)[k]} <b>{v}%</b></span><input type="range" value={v} onChange={e=>setValues({...values,[k]:+e.target.value})}/></label>)}</div>}</section>
  <section className="render"><div className="render-copy"><WandSparkles/><div><h2>{tr(done?"Your mix is ready":"Ready to make it hit?").toUpperCase()}</h2><p>{tr(done?"Check the balance, then export your mix as a WAV file.":"We’ll analyze every layer and turn it into one polished mix.")}</p></div></div><div className="render-actions">{done&&<button onClick={preview} className="preview-button">{playing?<Pause/>:<Play/>} {tr(playing?"Stop":"Preview").toUpperCase()}</button>}<button disabled={!tracks.length||mixing||downloading} onClick={done?download:start} className="render-button">{mixing?<><RotateCcw className="spin"/> MIXING...</>:downloading?<><RotateCcw className="spin"/> DOWNLOADING...</>:done?<><Download/> {tr("Download WAV").toUpperCase()}</>:<>{tr("Start auto mix").toUpperCase()} <ArrowRight/></>}</button></div></section>
  <footer><div className="brand"><span>M</span>MIXLAB</div><p>{tr("Make noise. Sound better.").toUpperCase()}</p><Link href="/dj"><Headphones/> {tr("Open DJ Studio").toUpperCase()} <ArrowRight/></Link></footer></main>
}

function PluginSlider({label,value,unit,min,max,onChange}:{label:string;value:number;unit:string;min:number;max:number;onChange:(value:number)=>void}){return <label><span>{label}<b>{value>0&&unit==="dB"?"+":""}{value} {unit}</b></span><input aria-label={label} type="range" min={min} max={max} value={value} onChange={e=>onChange(+e.target.value)}/></label>}

function connectPlugins(context:BaseAudioContext,source:AudioNode,destination:AudioNode,track:Track){const low=context.createBiquadFilter(),mid=context.createBiquadFilter(),high=context.createBiquadFilter(),compressor=context.createDynamicsCompressor(),gain=context.createGain();low.type="lowshelf";low.frequency.value=180;low.gain.value=track.plugins.low;mid.type="peaking";mid.frequency.value=1400;mid.Q.value=.8;mid.gain.value=track.plugins.mid;high.type="highshelf";high.frequency.value=6000;high.gain.value=track.plugins.high;compressor.threshold.value=-6-track.plugins.comp*.34;compressor.ratio.value=1+track.plugins.comp*.11;compressor.attack.value=.008;compressor.release.value=.18;gain.gain.value=track.gain/100;source.connect(low).connect(mid).connect(high).connect(compressor).connect(gain).connect(destination)}

function toWav(buffer:AudioBuffer){const channels=buffer.numberOfChannels,length=buffer.length*channels*2+44,out=new ArrayBuffer(length),view=new DataView(out);const write=(o:number,v:string)=>[...v].forEach((c,i)=>view.setUint8(o+i,c.charCodeAt(0)));write(0,"RIFF");view.setUint32(4,length-8,true);write(8,"WAVEfmt ");view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,channels,true);view.setUint32(24,buffer.sampleRate,true);view.setUint32(28,buffer.sampleRate*channels*2,true);view.setUint16(32,channels*2,true);view.setUint16(34,16,true);write(36,"data");view.setUint32(40,length-44,true);let o=44;for(let i=0;i<buffer.length;i++)for(let ch=0;ch<channels;ch++){const s=Math.max(-1,Math.min(1,buffer.getChannelData(ch)[i]));view.setInt16(o,s<0?s*0x8000:s*0x7fff,true);o+=2}return new Blob([out],{type:"audio/wav"})}
