"use client";
import Link from "next/link";
import { Disc3, Gauge, Headphones, Pause, Play, SkipBack, Upload, Volume2 } from "lucide-react";
import { useEffect, useRef, useState } from "react";

type DeckProps={side:"A"|"B";color:string;crossGain:number};
function Deck({side,color,crossGain}:DeckProps){
 const audio=useRef<HTMLAudioElement>(null); const [name,setName]=useState("NO TRACK LOADED"); const [url,setUrl]=useState(""); const [playing,setPlaying]=useState(false); const [pitch,setPitch]=useState(0); const [vol,setVol]=useState(80);
 useEffect(()=>{if(audio.current)audio.current.volume=(vol/100)*crossGain},[vol,crossGain]);
 const load=(f?:File)=>{if(!f)return;const u=URL.createObjectURL(f);setUrl(u);setName(f.name.replace(/\.[^.]+$/,"").toUpperCase())};
 const toggle=()=>{if(!audio.current||!url)return; playing?audio.current.pause():audio.current.play();setPlaying(!playing)};
 return <div className={`deck deck-${side.toLowerCase()}`} style={{"--deck":color} as React.CSSProperties}><div className="deck-head"><span>DECK {side}</span><div><b>{name}</b><small>{url?"READY • 00:00":"LOAD A TRACK TO BEGIN"}</small></div><label><Upload/> LOAD<input type="file" accept="audio/*" hidden onChange={e=>load(e.target.files?.[0])}/></label></div><div className="deck-body"><div className="platter-wrap"><div className={`platter ${playing?"rotating":""}`}><div className="vinyl-lines"/><div className="record-label"><Disc3/><b>MIX<br/>LAB</b></div></div><div className="tonearm"><i/><b/></div><div className="bpm"><small>BPM</small><strong>---.-</strong></div></div><div className="pitch"><span>+8</span><input type="range" min="-8" max="8" step="0.1" value={pitch} onChange={e=>{setPitch(+e.target.value);if(audio.current)audio.current.playbackRate=1+(+e.target.value/100)}}/><span>-8</span><b>{pitch>0?"+":""}{pitch.toFixed(1)}%</b></div></div><div className="deck-controls"><button><SkipBack/></button><button className="cue">CUE</button><button onClick={toggle} className="play">{playing?<Pause fill="currentColor"/>:<Play fill="currentColor"/>}</button><label><Volume2/><input type="range" value={vol} onChange={e=>{setVol(+e.target.value);if(audio.current)audio.current.volume=+e.target.value/100}}/></label></div><audio ref={audio} src={url} onEnded={()=>setPlaying(false)}/></div>
}
export default function DJ(){const [cross,setCross]=useState(50);return <main className="dj-page"><header><Link href="/" className="brand"><span>M</span>MIXLAB</Link><nav><Link href="/">AUTO MIX</Link><Link className="active" href="/dj">DJ STUDIO</Link></nav><div className="status"><i/> AUDIO ENGINE READY</div></header><section className="dj-title"><div><span>02 / LIVE MODE</span><h1>DJ STUDIO</h1></div><p>PCから音源を読み込んで、<br/>ブラウザですぐにプレイ。</p><div className="live"><i/> LIVE SESSION <b>00:00:00</b></div></section><section className="console"><Deck side="A" color="#c8ff36" crossGain={(100-cross)/100}/><div className="mixer"><div className="mixer-label">MIXER</div><div className="channel-pair">{["A","B"].map(x=><div className="channel" key={x}><b>CH {x}</b>{["GAIN","HI","MID","LOW"].map((n,i)=><label key={n}><span>{n}</span><input type="range" min="0" max="100" defaultValue={i?50:65}/></label>)}<div className="vu">{Array.from({length:12},(_,i)=><i className={i<5?"on":""} key={i}/>)}</div></div>)}</div><div className="cross"><span>CROSSFADER</span><input type="range" value={cross} onChange={e=>setCross(+e.target.value)}/><div><b>A</b><b>B</b></div></div><button className="headphone"><Headphones/> CUE MIX</button></div><Deck side="B" color="#b880ff" crossGain={cross/100}/></section><div className="dj-hint"><Gauge/><span><b>QUICK START</b> 音源を各デッキにロード → PLAY → クロスフェーダーでミックス</span><kbd>SPACE</kbd> PLAY / PAUSE</div></main>}
